name           = "REPL"
defaultTargets = ["repl"]

[[lean_lib]]
name = "REPL"

[[lean_exe]]
name               = "repl"
root               = "REPL.Main"
supportInterpreter = true

[[require]]
name = "mathlib"
git  = "https://github.com/leanprover-community/mathlib4.git"
rev  = "v4.11.0-rc1"
